import { Inter } from 'next/font/google'
import SideNav from './components/SideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Social Media | Home',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <div className='w-full relative h-screen flex'>
            <SideNav />
            {children}
        </div>
    )
}
