# Generated by Django 4.2.6 on 2023-10-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_userprofile_friends_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
    ]
