# Generated by Django 4.2.6 on 2023-10-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
